### ISSUE TITLE
add a counter of games played or won to the profile landing page (maybe below the avatar)

### ISSUE THREAD

**Issue by modmoto** [modmoto/w3champions-ui#18]

**Comment by filipslanchev** [comment]
total games makes more sense as total wins very often is easily seen a bit to the right on the race win rate 
![image](https://user-images.githubusercontent.com/5084019/83866551-a2cf8800-a730-11ea-82d8-7009f2810373.png)

**Comment by modmoto** [comment]
Also true, but the overview on the right is reset every season. Also games won is related to the profile pictures, so this should be nice to see for yourself (unless you want to hover to see it)
I was just thinking of wins, because sc2 has it this way aswell and i always found this pretty neat.
